apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1
  version: "1.30"

nodeGroups:
  - name: worker-node
    instanceType: t3.small
    desiredCapacity: 1