# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  namespace: jenkins
  labels:
    app: myapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-blue
  template:
    metadata:
      labels:
        app: myapp-blue
    spec:
      containers:
      - name: myapp
        image: satish680/my-app:latest