# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: myapp
        image: my-image:v1

# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: myapp
        image: my-image:v2

# single service pointing to either blue or green
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-blue  # or myapp-green
