# single service pointing to either blue or green
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: myapp-blue  # or myapp-green
  ports:
  - port: 3000
    targetPort: 3000
