# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  # namespace: jenkins
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: myapp
        image: satish680/my-app-python:latest
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  # namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
  - port: 5001
    targetPort: 5001